modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="kotlinforgemod"
version="${file.jarVersion}"
displayName="KotlinForgeMod"
authors="Nagisberry"
description='''
'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
